### ISSUE TITLE
take picture

### ISSUE THREAD

**Issue by ramiromoraes4** [harrowmykel/flutter_mobile_vision_2#5]
Congratulations on the migration,
 is there the possibility of taking a photo,
using a controller or any event as soon as the face is detected?
I need to send the image to the backend.

**Comment by ghost** [comment]
Hi, We recently worked on this.
Just pass the filename where you want to save the image to via imagePath and it will be saved there.
currently only .jpg is available


```
    //OPTIONAL: path to save image to. leave empty if you do not want to save the image
    imagePath: '', //'path/to/file.jpg'
```
